# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practica iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practica iOS
    pod 'FirebaseCrashlytics'
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'

  target 'Practica iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Practica iOSUITests' do
    # Pods for testing
  end

end
